### ISSUE TITLE
consumes upstream dependencies from prestosql.io

### ISSUE THREAD

**Issue by shawnzhu** [IBM/presto-db2#12]
## Today

in `pom.xml`:

```XML
...
<groupId>com.facebook.presto</groupId>
...
```

## Expectation

```XML
...
<groupId>io.prestosql</groupId>
...
```

Notice it starts to use new release version since the next revision after `0.215` is `300`.

**Comment by tooptoop4** [comment]
Y u not use fb 225?

**Comment by shawnzhu** [comment]
> Y u not use fb 225?

No, it starts to use dependencies from prestosql.io
