### ISSUE TITLE
checkstyle error

### ISSUE THREAD

**Issue by jameschuh** [IBM/presto-db2#17]
dears, 
when i run "mvn clean install " ,166 checkstyle errors happens, how to resolve it? thank u.

[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle) @ presto-db2 ---
[INFO] There are 166 errors reported by Checkstyle 8.7 with checkstyle/airbase-checks.xml ruleset.
[ERROR] src\main\java\io\prestosql\plugin\db2\DB2Client.java:[1] (regexp) RegexpMultiline: Line contains carriage return
[ERROR] src\main\java\io\prestosql\plugin\db2\DB2Client.java:[2] (regexp) RegexpMultiline: Line contains carriage return
[ERROR] src\main\java\io\prestosql\plugin\db2\DB2Client.java:[3] (regexp) RegexpMultiline: Line contains carriage return
[ERROR] src\main\java\io\prestosql\plugin\db2\DB2Client.java:[4] (regexp) RegexpMultiline: Line contains carriage return
[ERROR] src\main\java\io\prestosql\plugin\db2\DB2Client.java:[5] (regexp) RegexpMultiline: Line contains carriage return
[ERROR] src\main\java\io\prestosql\plugin\db2\DB2Client.java:[6] (regexp) RegexpMultiline: Line contains carriage return
[ERROR] src\main\java\io\prestosql\plugin\db2\DB2Client.java:[7] (regexp) RegexpMultiline: Line contains carriage return
[ERROR] src\main\java\io\prestosql\plugin\db2\DB2Client.java:[8] (regexp) RegexpMultiline: Line contains carriage return
[ERROR] src\main\java\io\prestosql\plugin\db2\DB2Client.java:[9] (regexp) RegexpMultiline: Line contains carriage return
[ERROR] src\main\java\io\prestosql\plugin\db2\DB2Client.java:[10] (regexp) RegexpMultiline: Line contains carriage return
[ERROR] src\main\java\io\prestosql\plugin\db2\DB2Client.java:[11] (regexp) RegexpMultiline: Line contains carriage return
[ERROR] src\main\java\io\prestosql\plugin\db2\DB2Client.java:[12] (regexp) RegexpMultiline: Line contains carriage return
[ERROR] src\main\java\io\prestosql\plugin\db2\DB2Client.java:[13] (regexp) RegexpMultiline: Line contains carriage return
[ERROR] src\main\java\io\prestosql\plugin\db2\DB2Client.java:[14] (regexp) RegexpMultiline: Line contains carriage return
[ERROR] src\main\java\io\prestosql\plugin\db2\DB2Client.java:[15] (regexp) RegexpMultiline: Line contains carriage return
[ERROR] src\main\java\io\prestosql\plugin\db2\DB2Client.java:[16] (regexp) RegexpMultiline: Line contains carriage return
[ERROR] src\main\java\io\prestosql\plugin\db2\DB2Client.java:[17] (regexp) RegexpMultiline: Line contains carriage return
[ERROR] src\main\java\io\prestosql\plugin\db2\DB2Client.java:[18] (regexp) RegexpMultiline: Line contains carriage return
[ERROR] src\main\java\io\prestosql\plugin\db2\DB2Client.java:[19] (regexp) RegexpMultiline: Line contains carriage return
[ERROR] src\main\java\io\prestosql\plugin\db2\DB2Client.java:[20] (regexp) RegexpMultiline: Line contains carriage return
[ERROR] src\main\java\io\prestosql\plugin\db2\DB2Client.java:[21] (regexp) RegexpMultiline: Line contains carriage return

**Comment by jameschuh** [comment]
when i add mvn parameters like this:

> mvn clean install -DskipTests -Dair.check.skip-all=true

errors occured as follow:

[ERROR] Failed to execute goal io.prestosql:presto-maven-plugin:5:generate-service-descriptor (default-generate-service-descriptor) on project presto-db2: Execution default-generate-service-descriptor of goal io.prestosql:presto-maven-plugin:5:generate-service-descriptor failed: A required class was missing while executing io.prestosql:presto-maven-plugin:5:generate-service-descriptor: io\prestosql\plugin\db2\DB2Client (wrong name: io/prestosql/plugin/db2/DB2Client)
[ERROR] -----------------------------------------------------
[ERROR] realm =    extension>io.prestosql:presto-maven-plugin:5
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/D:/ProgramFiles/.m2/repository/io/prestosql/presto-maven-plugin/5/presto-maven-plugin-5.jar
[ERROR] urls[1] = file:/D:/ProgramFiles/.m2/repository/com/google/guava/guava/14.0.1/guava-14.0.1.jar
[ERROR] urls[2] = file:/D:/ProgramFiles/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.17/plexus-utils-3.0.17.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

**Comment by shawnzhu** [comment]
I ran `mvn clean install` w/ [maven v3.5.2 official docker image](https://hub.docker.com/_/maven) and this what I got:

```SHELL
# mvn clean install -B -T C1
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ presto-db2 ---
[INFO] Deleting /presto-db2/target
[INFO] 
[INFO] --- presto-maven-plugin:5:check-spi-dependencies (default-check-spi-dependencies) @ presto-db2 ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (default) @ presto-db2 ---
[INFO] Ignoring requireUpperBoundDeps in org.codehaus.plexus:plexus-utils
[INFO] 
[INFO] --- dependency-scope-maven-plugin:0.8:check (default) @ presto-db2 ---
[INFO] No test dependency scope issues found
[INFO] 
[INFO] --- license-maven-plugin:2.3:check (default) @ presto-db2 ---
[INFO] Checking licenses...
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle) @ presto-db2 ---
[INFO] There are 4 errors reported by Checkstyle 8.7 with checkstyle/airbase-checks.xml ruleset.
[ERROR] src/main/java/io/prestosql/plugin/db2/DB2Client.java:[21] (imports) ImportOrder: Wrong order for 'com.ibm.db2.jcc.DB2Driver' import.
[ERROR] src/main/java/io/prestosql/plugin/db2/DB2ClientModule.java:[18] (imports) ImportOrder: Wrong order for 'com.google.inject.Binder' import.
[ERROR] src/test/java/io/prestosql/plugin/db2/TestDB2Plugin.java:[19] (imports) ImportOrder: Wrong order for 'com.google.common.collect.ImmutableMap' import.
[ERROR] src/test/java/io/prestosql/plugin/db2/TestDB2Plugin.java:[21] (imports) ImportOrder: Extra separation in import group before 'org.testng.annotations.Test'
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.266 s (Wall Clock)
[INFO] Finished at: 2019-08-30T18:29:10Z
[INFO] Final Memory: 42M/711M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (checkstyle) on project presto-db2: You have 4 Checkstyle violations. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

So I will try to fix these 4 checkstyle errors. However, I didn't see `166` violations.

**Comment by shawnzhu** [comment]
@jameschuh would you please retry (since I didn't see checkstyle violations anymore after :point_up: fix)?
