### ISSUE TITLE
Picks up prestosql v332

### ISSUE THREAD

**Issue by shawnzhu** [IBM/presto-db2#44]
See https://prestosql.io/docs/current/release/release-332.html

**Comment by AmoyDreaming** [comment]
Hello, Shawn.
PrestoSQL v334 will release soon with Oracle connect. Do you have plan to pick up v334? If so, v334 will archieve the milestone that able to connect all top 4 relational database (DB2, MySQL, Oracle, SqlServer).

**Comment by shawnzhu** [comment]
> PrestoSQL v334 will release soon with Oracle connect. Do you have plan to pick up v334?

Yes, I would love to pick up v332/v333 and v334 when it's available.

PR is also welcome and it could be very simple if there's connector SPI changes. E.g., https://github.com/IBM/presto-db2/pull/42
